name: "docs"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /app/node_modules
      - .:/app
    env_file:
      - .env
    ports:
      - "3000:3000"
    command: npm run serve --build
